#!/bin/bash

is_online() {
  nmcli networking connectivity
}

toggle() {
  if [[ "$(is_online)" == "limited" ]] || [[ "$(is_online)" == "full" ]]; then
    nmcli networking off
  else
    nmcli networking on
  fi
}

if [[ "$(is_online)" == "limited" ]] || [[ "$(is_online)" == "full" ]]; then
  STATUS="On"
  ICON="󰤨"
else
  STATUS="Off"
  ICON="󰤭"
fi

case "$1" in
--info) echo "[\"$ICON\",\"$STATUS\"]" ;;
--toggle) toggle ;;
esac
