#!/bin/bash

function startQS()
{
	$(which qs) kill
	env DISPLAY=:0 $(which qs) --daemonize
}

function startQSDebug()
{
	$(which qs) kill
	env DISPLAY=:0 $(which qs) 
}

function startPicom() 
{
	if [[ $(pidof picom) != "" ]]; then
  		killall picom
	fi
	picom --config $HOME/.config/picom/picom.conf > /dev/null 2>&1 & disown
}

function toggleBar()
{
	$(which qs) ipc call root toggleBar
}

function toggleLoadingScreen()
{
	$(which qs) ipc call root toggleLoadingScreen
}

function toggleSettings()
{
	$(which qs) ipc call root toggleSettings
}

function toggleLauncher() 
{
	$(which qs) ipc call root toggleLauncher
}

function toggleDashboard() {
	$(which qs) ipc call root toggleDashboard
}

function toggleMinimalMode() {
	$(which qs) ipc call root toggleMinimalMode
}

function setWall() {
	$(which qs) ipc call root setWallpaper $1
}

function clearNotifs() {
	$(which qs) ipc call root clearNotifs
}

case $1 in
--startQS) startQS ;;
--debug) startQSDebug ;;
--setConfig) setConfig ;;
--startHealthNotifier) startHealthNotifier ;;
--startPicom) startPicom ;;
--toggleBar) toggleBar ;;
--toggleLS) toggleLoadingScreen ;;
--toggleSettings) toggleSettings ;;
--toggleLauncher) toggleLauncher ;;
--toggleDashboard) toggleDashboard ;;
--toggleMinimalMode) toggleMinimalMode ;;
--setWall) setWall $2 ;;
--clearNotifs) clearNotifs ;;
esac
