#!/bin/bash

function start()
{
	$(which qs) kill
	env DISPLAY=:0 $(which qs) --daemonize
}

function startDebug()
{
	$(which qs) kill
	env DISPLAY=:0 $(which qs) 
}

function startPicom() 
{
	if [[ $(pidof picom) != "" ]]; then
  		killall picom
	fi
	picom --config $HOME/.config/picom/picom.conf > /dev/null 2>&1 & disown
}

function toggleBar()
{
	$(which qs) ipc call root toggleBar
}

function toggleLoadingScreen()
{
	$(which qs) ipc call root toggleLoadingScreen
}

function toggleSettings()
{
	$(which qs) ipc call root toggleSettings
}

function toggleLauncher() 
{
	$(which qs) ipc call root toggleLauncher
}

function toggleDashboard() {
	$(which qs) ipc call root toggleDashboard
}

function toggleMinimalMode() {
	$(which qs) ipc call root toggleMinimalMode
}

function setWall() {
	$(which qs) ipc call root setWallpaper $1
}

function clearNotifs() {
	$(which qs) ipc call root clearNotifs
}

function rebuildQuickshell() {
	cd ~
	if [[ $(ls quickshell-git) ]]; then
		cd quickshell-git
		git reset --hard origin/master
		git pull
		sudo cmake -GNinja -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWAYLAND=OFF -DSERVICE_PAM=OFF -DHYPRLAND=OFF
		sudo cmake --build build
		qs kill
		sudo cmake --install build
		qs --daemonize
	else
		echo "The 'quickshell-git' directory has not been found in the home directory. Did you follow the install instructions exactly?"
	fi
}

case $1 in
--start) start ;;
--debug) startDebug ;;
--setConfig) setConfig ;;
--startHealthNotifier) startHealthNotifier ;;
--startPicom) startPicom ;;
--toggleBar) toggleBar ;;
--toggleLS) toggleLoadingScreen ;;
--toggleSettings) toggleSettings ;;
--toggleLauncher) toggleLauncher ;;
--toggleDashboard) toggleDashboard ;;
--toggleMinimalMode) toggleMinimalMode ;;
--setWall) setWall $2 ;;
--clearNotifs) clearNotifs ;;
--updateQuickshell) rebuildQuickshell ;;
esac
