#!/bin/sh

function commit_and_stow() {
	if [[ $1 == "" ]]; then
		echo "Provide a commit message."
		exit 1
	fi
	cd $HOME/fibreglass

	printf "[*] Attemping to add ...\n"
	git add .
	git rm --cached $HOME/fibreglass/.config/quickshell/settings/settings.json
	git rm --cached $HOME/fibreglass/.config/scripts/ge
	git rm -r --cached $HOME/fibreglass/.config/helix/runtime
	git rm -r --cached $HOME/fibreglass/.github/fibreglass_icon_source
	printf "[i] Complete.\n"

	printf "[*] Attemping to commit ...\n"
	git commit -m $1
	printf "[i] Complete.\n"

	printf "[*] Attemping to stow ...\n"
	stow --adopt .
	printf "[i] Complete.\n"
}

function push() {
	cd $HOME/fibreglass

	printf "[*] Attemping to push ...\n"
	git push origin main
	printf "[i] Complete.\n"
}

function both() {
	commit_and_stow $1
	push
}

case $1 in
cs) commit_and_stow $2 ;;
p) push ;;
csp) both $2 ;;
esac
