#!/bin/bash

function startQS()
{
	$(which qs) -p $HOME/.config/fibreglass/quickshell kill
	env DISPLAY=:0 $(which qs) -p $HOME/.config/fibreglass/quickshell --daemonize
}

function startQSDebug()
{
	$(which qs) -p $HOME/.config/fibreglass/quickshell kill
        env DISPLAY=:0 $(which qs) -p $HOME/.config/fibreglass/quickshell
}

function setConfig()
{
	bspc config top_padding 20
	bspc config bottom_padding 55
	bspc config right_padding 20
	bspc config left_padding 20
	bspc config window_gap 10

	$HOME/.config/fibreglass/scripts/wallset_script
	$HOME/.config/fibreglass/scripts/setBorders.sh
}

function startHealthNotifier()
{
	if [[ $(pgrep -fl healthwarner.sh) ]]; then
 		 echo ""
	else
  		$HOME/.config/fibreglass/scripts/healthwarner.sh & disown
	fi
}

function startPicom() 
{
	if [[ $(pidof picom) != "" ]]; then
  		killall picom
	fi
	picom --config $HOME/.config/fibreglass/picom/picom.conf > /dev/null 2>&1 & disown
}

function toggleBar()
{
	$(which qs) -p $HOME/.config/fibreglass/quickshell ipc call root toggleBar
	pkill -f qsBarHide.sh
	$HOME/.config/fibreglass/scripts/qsBarHide.sh & disown
}

function toggleLoadingScreen()
{
	$(which qs) -p $HOME/.config/fibreglass/quickshell ipc call root toggleLoadingScreen
}

function toggleSettings()
{
	$(which qs) -p $HOME/.config/fibreglass/quickshell ipc call root toggleSettings
}



case $1 in
--startQS) startQS ;;
--debug) startQSDebug ;;
--setConfig) setConfig ;;
--startHealthNotifier) startHealthNotifier ;;
--startPicom) startPicom ;;
--toggleBar) toggleBar ;;
--toggleLS) toggleLoadingScreen ;;
--toggleSettings) toggleSettings ;;
esac
