#!/bin/bash

function startQS()
{
	$(which qs) -p $HOME/.config/fibreglass/quickshell kill
	env DISPLAY=:0 $(which qs) -p $HOME/.config/fibreglass/quickshell --daemonize
}

function startQSDebug()
{
	$(which qs) -p $HOME/.config/fibreglass/quickshell kill
        env DISPLAY=:0 $(which qs) -p $HOME/.config/fibreglass/quickshell
}

function startPicom() 
{
	if [[ $(pidof picom) != "" ]]; then
  		killall picom
	fi
	picom --config $HOME/.config/fibreglass/picom/picom.conf > /dev/null 2>&1 & disown
}

function toggleBar()
{
	$(which qs) -p $HOME/.config/fibreglass/quickshell ipc call root toggleBar
	pkill -f qsBarHide.sh
	$HOME/.config/fibreglass/scripts/qsBarHide.sh & disown
}

function toggleLoadingScreen()
{
	$(which qs) -p $HOME/.config/fibreglass/quickshell ipc call root toggleLoadingScreen
}

function toggleSettings()
{
	$(which qs) -p $HOME/.config/fibreglass/quickshell ipc call root toggleSettings
}

function toggleLauncher() 
{
	$(which qs) -p $HOME/.config/fibreglass/quickshell ipc call root toggleLauncher
}

function toggleDashboard() {
	$(which qs) -p $HOME/.config/fibreglass/quickshell ipc call root toggleDashboard
}

function setWall() {
	$(which qs) -p $HOME/.config/fibreglass/quickshell ipc call root setWallpaper $1
}

case $1 in
--startQS) startQS ;;
--debug) startQSDebug ;;
--setConfig) setConfig ;;
--startHealthNotifier) startHealthNotifier ;;
--startPicom) startPicom ;;
--toggleBar) toggleBar ;;
--toggleLS) toggleLoadingScreen ;;
--toggleSettings) toggleSettings ;;
--toggleLauncher) toggleLauncher ;;
--toggleDashboard) toggleDashboard ;;
--setWall) setWall $2 ;;
esac
