backend = "fastresize"
palette = "dark"
check_contrast = true

[templates]
kitty.template = "kitty.conf"
kitty.target = "~/.config/kitty/colours.conf"

openbox.template = "openbox_themerc"
openbox.target = "~/.themes/minimal/openbox-3/themerc"

waybar.template = "waybar.css"
waybar.target = "~/.config/waybar/colors.css"

alacritty.template = "alacritty.toml"
alacritty.target = "~/.config/alacritty/colors.toml"
