#!/bin/bash

current_governor=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
available_governors=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors)

printf "The current mode is %s\n" "$current_governor"
printf "The available modes are: %s\n" "$available_governors"

read -p "Mode change (perf/save): " modechange

mode=""

if [[ "$modechange" == "perf" ]]; then
  mode="performance"
elif [[ "$modechange" == "save" ]]; then
  mode="powersave"
else
  exit
fi

sudo cpupower frequency-set --governor $mode
