pragma Singleton

import QtQuick
import Quickshell

Singleton {

	readonly property string background: "#16130b"
	readonly property string error: "#ffb4ab"
	readonly property string error_container: "#93000a"
	readonly property string inverse_on_surface: "#333027"
	readonly property string inverse_primary: "#6e5d0e"
	readonly property string inverse_surface: "#e9e2d4"
	readonly property string on_background: "#e9e2d4"
	readonly property string on_error: "#690005"
	readonly property string on_error_container: "#ffdad6"
	readonly property string on_primary: "#3a3000"
	readonly property string on_primary_container: "#f9e287"
	readonly property string on_primary_fixed: "#221b00"
	readonly property string on_primary_fixed_variant: "#544600"
	readonly property string on_secondary: "#373016"
	readonly property string on_secondary_container: "#eee2bc"
	readonly property string on_secondary_fixed: "#211b04"
	readonly property string on_secondary_fixed_variant: "#4e472a"
	readonly property string on_surface: "#e9e2d4"
	readonly property string on_surface_variant: "#cdc6b4"
	readonly property string on_tertiary: "#153722"
	readonly property string on_tertiary_container: "#c5ecce"
	readonly property string on_tertiary_fixed: "#00210f"
	readonly property string on_tertiary_fixed_variant: "#2c4e38"
	readonly property string outline: "#969080"
	readonly property string outline_variant: "#4b4739"
	readonly property string primary: "#dcc66e"
	readonly property string primary_container: "#544600"
	readonly property string primary_fixed: "#f9e287"
	readonly property string primary_fixed_dim: "#dcc66e"
	readonly property string scrim: "#000000"
	readonly property string secondary: "#d2c6a1"
	readonly property string secondary_container: "#4e472a"
	readonly property string secondary_fixed: "#eee2bc"
	readonly property string secondary_fixed_dim: "#d2c6a1"
	readonly property string shadow: "#000000"
	readonly property string source_color: "#cac3b2"
	readonly property string surface: "#16130b"
	readonly property string surface_bright: "#3c3930"
	readonly property string surface_container: "#221f17"
	readonly property string surface_container_high: "#2d2a21"
	readonly property string surface_container_highest: "#38352b"
	readonly property string surface_container_low: "#1e1b13"
	readonly property string surface_container_lowest: "#100e07"
	readonly property string surface_dim: "#16130b"
	readonly property string surface_tint: "#dcc66e"
	readonly property string surface_variant: "#4b4739"
	readonly property string tertiary: "#aad0b2"
	readonly property string tertiary_container: "#2c4e38"
	readonly property string tertiary_fixed: "#c5ecce"
	readonly property string tertiary_fixed_dim: "#aad0b2"
}
