# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0E0E0E"
foreground = "#DCDCDC"

[colors.normal]
black   = "#393939"
red     = "#554847"
green   = "#636764"
yellow  = "#716766"
blue    = "#767D79"
magenta = "#767C7B"
cyan    = "#9B9B9A"
white   = "#C5C5C4"

[colors.bright]
black   = "#8A8A89"
red     = "#554847"
green   = "#636764"
yellow  = "#716766"
blue    = "#767D79"
magenta = "#767C7B"
cyan    = "#9B9B9A"
white   = "#C5C5C4"

