# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#191919"
foreground = "#DFE4E0"

[colors.normal]
black   = "#434444"
red     = "#52655A"
green   = "#6A8186"
yellow  = "#67896D"
blue    = "#7C847F"
magenta = "#6A9267"
cyan    = "#A4B3A6"
white   = "#C9D1CA"

[colors.bright]
black   = "#8D928D"
red     = "#52655A"
green   = "#6A8186"
yellow  = "#67896D"
blue    = "#7C847F"
magenta = "#6A9267"
cyan    = "#A4B3A6"
white   = "#C9D1CA"

