# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#212425"
foreground = "#E6E7E4"

[colors.normal]
black   = "#4C4F51"
red     = "#676E5C"
green   = "#818C96"
yellow  = "#888E6D"
blue    = "#9192BC"
magenta = "#A4B46C"
cyan    = "#B8BAB3"
white   = "#D3D4D1"

[colors.bright]
black   = "#949492"
red     = "#676E5C"
green   = "#818C96"
yellow  = "#888E6D"
blue    = "#9192BC"
magenta = "#A4B46C"
cyan    = "#B8BAB3"
white   = "#D3D4D1"

