# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0E0E0D"
foreground = "#F3F4F5"

[colors.normal]
black   = "#383938"
red     = "#454741"
green   = "#837061"
yellow  = "#6B7F73"
blue    = "#BF6C20"
magenta = "#928986"
cyan    = "#DEDFE3"
white   = "#E6E7E9"

[colors.bright]
black   = "#A1A1A3"
red     = "#454741"
green   = "#837061"
yellow  = "#6B7F73"
blue    = "#BF6C20"
magenta = "#928986"
cyan    = "#DEDFE3"
white   = "#E6E7E9"

