[colors.primary]
background = '#141314'
foreground = '#e5e2e2'
 
[colors.cursor]
text = '#e5e2e2'
cursor = '#c7c6cb' 
 
[colors.vi_mode_cursor]
text = '#141314'
cursor = '#eeedf4' 
 
[colors.search.matches]
foreground = '#46464b' 
background = '#f8eaf1' 
 
[colors.search.focused_match]
foreground = '#46464b' 
background = '#eeedf4' 
 
[colors.footer_bar]
foreground = '#46464b' 
background = '#e5e2e2' 
 
[colors.hints.start]
foreground = '#46464b' 
background = '#c8c6c9' 
 
[colors.hints.end]
foreground = '#46464b' 
background = '#c8c6c9' 
 
[colors.selection]
text = '#141314'
background = '#eeedf4'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#eeedf4' 
yellow = '#5d5e64' 
blue = '#eeedf4' 
magenta = '#f8eaf1' 
cyan = '#c8c6c9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
